/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AzkarMassaRouteImport } from './routes/azkar-massa'
import { Route as AzkarSabahRouteImport } from './routes/azkar-sabah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarMassaRoute = AzkarMassaRouteImport.update({
  id: '/azkar-massa',
  path: '/azkar-massa',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarSabahRoute = AzkarSabahRouteImport.update({
  id: '/azkar-sabah',
  path: '/azkar-sabah',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/azkar-massa': typeof AzkarMassaRoute
  '/azkar-sabah': typeof AzkarSabahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/azkar-massa': typeof AzkarMassaRoute
  '/azkar-sabah': typeof AzkarSabahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/azkar-massa': typeof AzkarMassaRoute
  '/azkar-sabah': typeof AzkarSabahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/azkar-massa' | '/azkar-sabah'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/azkar-massa' | '/azkar-sabah'
  id: '__root__' | '/' | '/azkar-massa' | '/azkar-sabah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AzkarMassaRoute: typeof AzkarMassaRoute
  AzkarSabahRoute: typeof AzkarSabahRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar-massa': {
      id: '/azkar-massa'
      path: '/azkar-massa'
      fullPath: '/azkar-massa'
      preLoaderRoute: typeof AzkarMassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar-sabah': {
      id: '/azkar-sabah'
      path: '/azkar-sabah'
      fullPath: '/azkar-sabah'
      preLoaderRoute: typeof AzkarSabahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AzkarMassaRoute: AzkarMassaRoute,
  AzkarSabahRoute: AzkarSabahRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
