/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AzkarBaadAlfajrWalmaghribRouteImport } from './routes/azkar-baad-alfajr-walmaghrib'
import { Route as AzkarBaadSalahRouteImport } from './routes/azkar-baad-salah'
import { Route as AzkarMassaRouteImport } from './routes/azkar-massa'
import { Route as AzkarNawmRouteImport } from './routes/azkar-nawm'
import { Route as AzkarSabahRouteImport } from './routes/azkar-sabah'
import { Route as SeoStatusRouteImport } from './routes/seo-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarBaadAlfajrWalmaghribRoute =
  AzkarBaadAlfajrWalmaghribRouteImport.update({
    id: '/azkar-baad-alfajr-walmaghrib',
    path: '/azkar-baad-alfajr-walmaghrib',
    getParentRoute: () => rootRouteImport,
  } as any)
const AzkarBaadSalahRoute = AzkarBaadSalahRouteImport.update({
  id: '/azkar-baad-salah',
  path: '/azkar-baad-salah',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarMassaRoute = AzkarMassaRouteImport.update({
  id: '/azkar-massa',
  path: '/azkar-massa',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarNawmRoute = AzkarNawmRouteImport.update({
  id: '/azkar-nawm',
  path: '/azkar-nawm',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarSabahRoute = AzkarSabahRouteImport.update({
  id: '/azkar-sabah',
  path: '/azkar-sabah',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoStatusRoute = SeoStatusRouteImport.update({
  id: '/seo-status',
  path: '/seo-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/azkar-baad-alfajr-walmaghrib': typeof AzkarBaadAlfajrWalmaghribRoute
  '/azkar-baad-salah': typeof AzkarBaadSalahRoute
  '/azkar-massa': typeof AzkarMassaRoute
  '/azkar-nawm': typeof AzkarNawmRoute
  '/azkar-sabah': typeof AzkarSabahRoute
  '/seo-status': typeof SeoStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/azkar-baad-alfajr-walmaghrib': typeof AzkarBaadAlfajrWalmaghribRoute
  '/azkar-baad-salah': typeof AzkarBaadSalahRoute
  '/azkar-massa': typeof AzkarMassaRoute
  '/azkar-nawm': typeof AzkarNawmRoute
  '/azkar-sabah': typeof AzkarSabahRoute
  '/seo-status': typeof SeoStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/azkar-baad-alfajr-walmaghrib': typeof AzkarBaadAlfajrWalmaghribRoute
  '/azkar-baad-salah': typeof AzkarBaadSalahRoute
  '/azkar-massa': typeof AzkarMassaRoute
  '/azkar-nawm': typeof AzkarNawmRoute
  '/azkar-sabah': typeof AzkarSabahRoute
  '/seo-status': typeof SeoStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/azkar-baad-alfajr-walmaghrib'
    | '/azkar-baad-salah'
    | '/azkar-massa'
    | '/azkar-nawm'
    | '/azkar-sabah'
    | '/seo-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/azkar-baad-alfajr-walmaghrib'
    | '/azkar-baad-salah'
    | '/azkar-massa'
    | '/azkar-nawm'
    | '/azkar-sabah'
    | '/seo-status'
  id:
    | '__root__'
    | '/'
    | '/azkar-baad-alfajr-walmaghrib'
    | '/azkar-baad-salah'
    | '/azkar-massa'
    | '/azkar-nawm'
    | '/azkar-sabah'
    | '/seo-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AzkarBaadAlfajrWalmaghribRoute: typeof AzkarBaadAlfajrWalmaghribRoute
  AzkarBaadSalahRoute: typeof AzkarBaadSalahRoute
  AzkarMassaRoute: typeof AzkarMassaRoute
  AzkarNawmRoute: typeof AzkarNawmRoute
  AzkarSabahRoute: typeof AzkarSabahRoute
  SeoStatusRoute: typeof SeoStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar-baad-alfajr-walmaghrib': {
      id: '/azkar-baad-alfajr-walmaghrib'
      path: '/azkar-baad-alfajr-walmaghrib'
      fullPath: '/azkar-baad-alfajr-walmaghrib'
      preLoaderRoute: typeof AzkarBaadAlfajrWalmaghribRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar-baad-salah': {
      id: '/azkar-baad-salah'
      path: '/azkar-baad-salah'
      fullPath: '/azkar-baad-salah'
      preLoaderRoute: typeof AzkarBaadSalahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar-massa': {
      id: '/azkar-massa'
      path: '/azkar-massa'
      fullPath: '/azkar-massa'
      preLoaderRoute: typeof AzkarMassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar-nawm': {
      id: '/azkar-nawm'
      path: '/azkar-nawm'
      fullPath: '/azkar-nawm'
      preLoaderRoute: typeof AzkarNawmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar-sabah': {
      id: '/azkar-sabah'
      path: '/azkar-sabah'
      fullPath: '/azkar-sabah'
      preLoaderRoute: typeof AzkarSabahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-status': {
      id: '/seo-status'
      path: '/seo-status'
      fullPath: '/seo-status'
      preLoaderRoute: typeof SeoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AzkarBaadAlfajrWalmaghribRoute: AzkarBaadAlfajrWalmaghribRoute,
  AzkarBaadSalahRoute: AzkarBaadSalahRoute,
  AzkarMassaRoute: AzkarMassaRoute,
  AzkarNawmRoute: AzkarNawmRoute,
  AzkarSabahRoute: AzkarSabahRoute,
  SeoStatusRoute: SeoStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
